/*
 * Copyright (c) 2008-2013 Spotfire AB,
 * Första Långgatan 26, SE-413 28 Göteborg, Sweden.
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of Spotfire AB ("Confidential Information"). You shall not
 * disclose such Confidential Information and may not use it in any way,
 * absent an express written license agreement between you and Spotfire AB
 * or TIBCO Software Inc. that authorizes such use.
 */

-- ================================
--  Report errors
-- ================================

WHENEVER SQLERROR EXIT FAILURE OR EXIT 1

-- ================================
--      Create Database Schema
-- ================================


DECLARE
  C INT;
BEGIN
  SELECT COUNT(*) INTO C FROM USER_TABLES WHERE UPPER(TABLE_NAME) = UPPER('ACTIONLOG');
  IF C = 0 THEN
	  EXECUTE IMMEDIATE 'CREATE TABLE ACTIONLOG (
			LOGGED_TIME TIMESTAMP NOT NULL,
			MACHINE NVARCHAR2(100) NOT NULL,
			USER_NAME NVARCHAR2(402),
			ORIGINAL_TIME TIMESTAMP,
			ORIGINAL_IP NVARCHAR2(100),
			LOG_CATEGORY NVARCHAR2(30),
			LOG_ACTION NVARCHAR2(30),
			SUCCESS CHAR(1),
			SESSION_ID CHAR(36),
			ID1 NVARCHAR2(400),
			ID2 NVARCHAR2(400),
			ARG1 NVARCHAR2(400),
			ARG2 NVARCHAR2(400),
			ARG3 NVARCHAR2(400),
			ARG4 NVARCHAR2(400),
			ARG5 NVARCHAR2(400),
			ARG6 NVARCHAR2(400))';

    -- Optional indices, uncomment if needed.
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_LOGGED_TIME ON ACTIONLOG(LOGGED_TIME)';
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_MACHINE ON ACTIONLOG(MACHINE)';
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_USER_NAME ON ACTIONLOG(USER_NAME)';
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_ORIGINAL_TIME ON ACTIONLOG(ORIGINAL_TIME)';
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_ORIGINAL_IP ON ACTIONLOG(ORIGINAL_IP)';
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_LOG_CATEGORY ON ACTIONLOG(LOG_CATEGORY)';
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_LOG_ACTION ON ACTIONLOG(LOG_ACTION)';
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_LOG_CATEGORY_ACTION ON ACTIONLOG(LOG_CATEGORY,LOG_ACTION)';
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_SESSION_ID ON ACTIONLOG(SESSION_ID)';
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_ID1 ON ACTIONLOG(ID1)';
		-- EXECUTE IMMEDIATE 'CREATE INDEX I_ID2 ON ACTIONLOG(ID2)';
  END IF;
END;
/


-- The views below are used by the information model
-- but the all the storage is done in the actionlog table
CREATE OR REPLACE VIEW UTC_TIME AS SELECT SYS_EXTRACT_UTC(SYSTIMESTAMP) AS TS FROM DUAL
/

CREATE OR REPLACE VIEW LIBRARY_WP_CLONE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH FROM ACTIONLOG WHERE LOG_CATEGORY = 'library_wp' AND LOG_ACTION = 'clone'
/

CREATE OR REPLACE VIEW DAT_CON_PRO_CREATE_CONNECTION  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION, ARG3 AS DATASOURCELIBRARYID FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_pro' AND LOG_ACTION = 'create_connection'
/

CREATE OR REPLACE VIEW DAT_CON_WP_CREATE_CONNECTION  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION, ARG3 AS DATASOURCELIBRARYID FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_wp' AND LOG_ACTION = 'create_connection'
/

CREATE OR REPLACE VIEW DAT_CON_PRO_CREATE_SOURCE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_pro' AND LOG_ACTION = 'create_source'
/

CREATE OR REPLACE VIEW DAT_CON_WP_CREATE_SOURCE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_wp' AND LOG_ACTION = 'create_source'
/

CREATE OR REPLACE VIEW DATAFUNCTION_PRO_EXECUTE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNUSED, ID2 AS PATH, ARG1 AS PARAMS, ARG2 AS DURATION FROM ACTIONLOG WHERE LOG_CATEGORY = 'datafunction_pro' AND LOG_ACTION = 'execute'
/

CREATE OR REPLACE VIEW DATAFUNCTION_WP_EXECUTE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNUSED, ID2 AS PATH, ARG1 AS PARAMS, ARG2 AS DURATION FROM ACTIONLOG WHERE LOG_CATEGORY = 'datafunction_wp' AND LOG_ACTION = 'execute'
/

CREATE OR REPLACE VIEW DATASOURCE_PRO_EXECUTE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNUSED, ID2 AS PATH, ARG1 AS TITLE, ARG2 AS PARAMS, ARG3 AS DURATION, ARG4 AS NUMROWS FROM ACTIONLOG WHERE LOG_CATEGORY = 'datasource_pro' AND LOG_ACTION = 'execute'
/

CREATE OR REPLACE VIEW DATASOURCE_WP_EXECUTE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNUSED, ID2 AS PATH, ARG1 AS TITLE, ARG2 AS PARAMS, ARG3 AS DURATION, ARG4 AS NUMROWS FROM ACTIONLOG WHERE LOG_CATEGORY = 'datasource_wp' AND LOG_ACTION = 'execute'
/

CREATE OR REPLACE VIEW DAT_CON_PRO_GET_DATA  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION, ARG3 AS INTERNALQUERY, ARG4 AS NUMROWS, ARG5 AS DURATION, ARG6 AS EXTERNALQUERY FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_pro' AND LOG_ACTION = 'get_data'
/

CREATE OR REPLACE VIEW DAT_CON_WP_GET_DATA  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION, ARG3 AS INTERNALQUERY, ARG4 AS NUMROWS, ARG5 AS DURATION, ARG6 AS EXTERNALQUERY FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_wp' AND LOG_ACTION = 'get_data'
/

CREATE OR REPLACE VIEW LIBRARY_PRO_CLOSE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH FROM ACTIONLOG WHERE LOG_CATEGORY = 'library_pro' AND LOG_ACTION = 'close'
/

CREATE OR REPLACE VIEW LIBRARY_WP_CLOSE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH FROM ACTIONLOG WHERE LOG_CATEGORY = 'library_wp' AND LOG_ACTION = 'close'
/

CREATE OR REPLACE VIEW DAT_CON_PRO_LOAD_CONNECTION  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION, ARG3 AS DATASOURCELIBRARYID FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_pro' AND LOG_ACTION = 'load_connection'
/

CREATE OR REPLACE VIEW DAT_CON_WP_LOAD_CONNECTION  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION, ARG3 AS DATASOURCELIBRARYID FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_wp' AND LOG_ACTION = 'load_connection'
/

CREATE OR REPLACE VIEW FILE_PRO_LOAD  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNUSED, ID2 AS PATH FROM ACTIONLOG WHERE LOG_CATEGORY = 'file_pro' AND LOG_ACTION = 'load'
/

CREATE OR REPLACE VIEW FILE_WP_LOAD  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNUSED, ID2 AS PATH FROM ACTIONLOG WHERE LOG_CATEGORY = 'file_wp' AND LOG_ACTION = 'load'
/

CREATE OR REPLACE VIEW LIBRARY_AS_LOAD  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH FROM ACTIONLOG WHERE LOG_CATEGORY = 'library_as' AND LOG_ACTION = 'load'
/

CREATE OR REPLACE VIEW LIBRARY_PRO_LOAD  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH FROM ACTIONLOG WHERE LOG_CATEGORY = 'library_pro' AND LOG_ACTION = 'load'
/

CREATE OR REPLACE VIEW LIBRARY_WP_LOAD  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH FROM ACTIONLOG WHERE LOG_CATEGORY = 'library_wp' AND LOG_ACTION = 'load'
/

CREATE OR REPLACE VIEW DAT_CON_PRO_LOAD_SOURCE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_pro' AND LOG_ACTION = 'load_source'
/

CREATE OR REPLACE VIEW DAT_CON_WP_LOAD_SOURCE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_wp' AND LOG_ACTION = 'load_source'
/

CREATE OR REPLACE VIEW ADMIN_GROUP_ADD_MEMBER  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS NAME, ID2 AS GNAME, ARG1 AS SORT, ARG2 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'admin' AND LOG_ACTION = 'group_add_member'
/

CREATE OR REPLACE VIEW ANALYSIS_PRO_APPLY_BOOKMARK  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS BOOKMARKNAME, ARG2 AS UNUSED, ARG3 AS WPSESSIONID, ARG4 AS WEBANALYSISID FROM ACTIONLOG WHERE LOG_CATEGORY = 'analysis_pro' AND LOG_ACTION = 'apply_bookmark'
/

CREATE OR REPLACE VIEW ANALYSIS_WP_APPLY_BOOKMARK  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS BOOKMARKNAME, ARG2 AS UNUSED, ARG3 AS WPSESSIONID, ARG4 AS WEBANALYSISID FROM ACTIONLOG WHERE LOG_CATEGORY = 'analysis_wp' AND LOG_ACTION = 'apply_bookmark'
/

CREATE OR REPLACE VIEW ANALYSIS_PRO_SET_PAGE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS PAGENAME, ARG2 AS UNUSED, ARG3 AS WPSESSIONID, ARG4 AS WEBANALYSISID FROM ACTIONLOG WHERE LOG_CATEGORY = 'analysis_pro' AND LOG_ACTION = 'set_page'
/

CREATE OR REPLACE VIEW ANALYSIS_WP_SET_PAGE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS PAGENAME, ARG2 AS UNUSED, ARG3 AS WPSESSIONID, ARG4 AS WEBANALYSISID FROM ACTIONLOG WHERE LOG_CATEGORY = 'analysis_wp' AND LOG_ACTION = 'set_page'
/

CREATE OR REPLACE VIEW AUTOMATION_JOB_AS_JOB_FINISHED  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS JOBID, ARG2 AS STATUS, ARG3 AS EXECUTIONTIME, ARG4 AS MESSAGE FROM ACTIONLOG WHERE LOG_CATEGORY = 'automation_job_as' AND LOG_ACTION = 'job_finished'
/

CREATE OR REPLACE VIEW AUTOMATION_JOB_AS_JOB_STARTED  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS JOBID, ARG2 AS STATUS, ARG3 AS EXECUTIONTIME, ARG4 AS MESSAGE FROM ACTIONLOG WHERE LOG_CATEGORY = 'automation_job_as' AND LOG_ACTION = 'job_started'
/

CREATE OR REPLACE VIEW ADMIN_CREATE_GROUP  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS GNAME, ID2 AS DISPLAYNAME, ARG1 AS EMAIL FROM ACTIONLOG WHERE LOG_CATEGORY = 'admin' AND LOG_ACTION = 'create_group'
/

CREATE OR REPLACE VIEW ADMIN_CREATE_USER  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNAME, ID2 AS DISPLAYNAME, ARG1 AS EMAIL FROM ACTIONLOG WHERE LOG_CATEGORY = 'admin' AND LOG_ACTION = 'create_user'
/

CREATE OR REPLACE VIEW AUTH_IMPERSONATE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNAME FROM ACTIONLOG WHERE LOG_CATEGORY = 'auth' AND LOG_ACTION = 'impersonate'
/

CREATE OR REPLACE VIEW INFO_LINK_CREATE_IL  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH FROM ACTIONLOG WHERE LOG_CATEGORY = 'info_link' AND LOG_ACTION = 'create_il'
/

CREATE OR REPLACE VIEW INFO_LINK_GET_DATA  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS DURATION, ARG2 AS SIZEB, ARG3 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'info_link' AND LOG_ACTION = 'get_data'
/

CREATE OR REPLACE VIEW INFO_LINK_LOAD_IL  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'info_link' AND LOG_ACTION = 'load_il'
/

CREATE OR REPLACE VIEW INFO_LINK_UPDATE_IL  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH FROM ACTIONLOG WHERE LOG_CATEGORY = 'info_link' AND LOG_ACTION = 'update_il'
/

CREATE OR REPLACE VIEW LIBRARY_COPY  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS LIBRARYTYPE, ARG2 AS DESTLIBRARYID, ARG3 AS DESTPATH, ARG4 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'copy'
/

CREATE OR REPLACE VIEW LIBRARY_CREATE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS LIBRARYTYPE, ARG2 AS PRESIZE, ARG3 AS POSTSIZE FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'create'
/

CREATE OR REPLACE VIEW LIBRARY_DELETE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS LIBRARYTYPE, ARG2 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'delete'
/

CREATE OR REPLACE VIEW LIBRARY_EXPORT  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS DESTPATH, ARG2 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'export'
/

CREATE OR REPLACE VIEW LIBRARY_IMPORT  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS DESTPATH, ARG2 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'import'
/

CREATE OR REPLACE VIEW LIBRARY_LOAD_CONTENT  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS LIBRARYTYPE, ARG2 AS DURATION, ARG3 AS SIZEB, ARG4 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'load_content'
/

CREATE OR REPLACE VIEW LIBRARY_MOVE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS LIBRARYTYPE, ARG2 AS DESTLIBRARYID, ARG3 AS DESTPATH, ARG4 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'move'
/

CREATE OR REPLACE VIEW LIBRARY_REMOVE_PERM  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS NAME, ARG2 AS SORT FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'remove_perm'
/

CREATE OR REPLACE VIEW LIBRARY_SAVE_CONTENT  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS LIBRARYTYPE, ARG2 AS PRESIZE, ARG3 AS POSTSIZE FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'save_content'
/

CREATE OR REPLACE VIEW LIBRARY_SET_GROUP_PERM  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS GNAME, ARG2 AS PERMISSION, ARG3 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'set_group_perm'
/

CREATE OR REPLACE VIEW LIBRARY_SET_USER_PERM  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS PATH, ARG1 AS UNAME, ARG2 AS PERMISSION, ARG3 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'library' AND LOG_ACTION = 'set_user_perm'
/

CREATE OR REPLACE VIEW LIBRARY_WP_UPDATE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS UNUSED1, ARG2 AS UNUSED2, ARG3 AS WPSESSIONID FROM ACTIONLOG WHERE LOG_CATEGORY = 'library_wp' AND LOG_ACTION = 'update'
/

CREATE OR REPLACE VIEW ADMIN_REMOVE_LICENSE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS GNAME, ID2 AS LICENSENAME FROM ACTIONLOG WHERE LOG_CATEGORY = 'admin' AND LOG_ACTION = 'remove_license'
/

CREATE OR REPLACE VIEW ADMIN_SET_LICENSE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS GNAME, ID2 AS LICENSENAME, ARG1 AS EXCLUDINGFUNCTION FROM ACTIONLOG WHERE LOG_CATEGORY = 'admin' AND LOG_ACTION = 'set_license'
/

CREATE OR REPLACE VIEW AUTH_LOGIN  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS CLIENTTYPE, ID2 AS CLIENTVER, ARG1 AS DISPLAYNAME, ARG2 AS EMAIL FROM ACTIONLOG WHERE LOG_CATEGORY = 'auth' AND LOG_ACTION = 'login'
/

CREATE OR REPLACE VIEW AUTH_LOGOUT  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNAME FROM ACTIONLOG WHERE LOG_CATEGORY = 'auth' AND LOG_ACTION = 'logout'
/

CREATE OR REPLACE VIEW MONITORING_AVERAGE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS MEASURE, ID2 AS UNUSED, ARG1 AS MEAN, ARG2 AS MIN, ARG3 AS MAX FROM ACTIONLOG WHERE LOG_CATEGORY = 'monitoring' AND LOG_ACTION = 'average'
/

CREATE OR REPLACE VIEW MONITORING_WP_AVERAGE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS MEASURE, ID2 AS UNUSED, ARG1 AS MEAN, ARG2 AS MIN, ARG3 AS MAX FROM ACTIONLOG WHERE LOG_CATEGORY = 'monitoring_wp' AND LOG_ACTION = 'average'
/

CREATE OR REPLACE VIEW MONITORING_MEASUREMENT  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS MEASURE, ID2 AS UNUSED, ARG1 AS VALUE FROM ACTIONLOG WHERE LOG_CATEGORY = 'monitoring' AND LOG_ACTION = 'measurement'
/

CREATE OR REPLACE VIEW ADMIN_SET_PREFERENCE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS NAME, ID2 AS PREFTYPE, ARG1 AS CATEGORY, ARG2 AS ID FROM ACTIONLOG WHERE LOG_CATEGORY = 'admin' AND LOG_ACTION = 'set_preference'
/

CREATE OR REPLACE VIEW ADMIN_REMOVE_PRINCIPAL  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS NAME, ID2 AS SORT, ARG1 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'admin' AND LOG_ACTION = 'remove_principal'
/

CREATE OR REPLACE VIEW ADMIN_GROUP_REMOVE_MEMBER  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS NAME, ID2 AS GNAME, ARG1 AS SORT, ARG2 AS GROUPINGID FROM ACTIONLOG WHERE LOG_CATEGORY = 'admin' AND LOG_ACTION = 'group_remove_member'
/

CREATE OR REPLACE VIEW ADMIN_RENAME_PRINCIPAL  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS OLDNAME, ID2 AS NEWNAME, ARG1 AS SORT FROM ACTIONLOG WHERE LOG_CATEGORY = 'admin' AND LOG_ACTION = 'rename_principal'
/

CREATE OR REPLACE VIEW ADMIN_CHANGE_PASSWD  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNAME FROM ACTIONLOG WHERE LOG_CATEGORY = 'admin' AND LOG_ACTION = 'change_passwd'
/

CREATE OR REPLACE VIEW AUTH_AS_LOGIN  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNAME FROM ACTIONLOG WHERE LOG_CATEGORY = 'auth_as' AND LOG_ACTION = 'login'
/

CREATE OR REPLACE VIEW AUTH_PRO_LOGIN  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNAME FROM ACTIONLOG WHERE LOG_CATEGORY = 'auth_pro' AND LOG_ACTION = 'login'
/

CREATE OR REPLACE VIEW AUTH_WP_LOGIN  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNAME FROM ACTIONLOG WHERE LOG_CATEGORY = 'auth_wp' AND LOG_ACTION = 'login'
/

CREATE OR REPLACE VIEW AUTH_AS_LOGOUT  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNAME FROM ACTIONLOG WHERE LOG_CATEGORY = 'auth_as' AND LOG_ACTION = 'logout'
/

CREATE OR REPLACE VIEW AUTH_PRO_LOGOUT  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNAME FROM ACTIONLOG WHERE LOG_CATEGORY = 'auth_pro' AND LOG_ACTION = 'logout'
/

CREATE OR REPLACE VIEW AUTH_WP_LOGOUT  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS UNAME FROM ACTIONLOG WHERE LOG_CATEGORY = 'auth_wp' AND LOG_ACTION = 'logout'
/

CREATE OR REPLACE VIEW MONITORING_WP_COUNTER  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS MEASURE, ID2 AS UNUSED, ARG1 AS VALUE FROM ACTIONLOG WHERE LOG_CATEGORY = 'monitoring_wp' AND LOG_ACTION = 'counter'
/

CREATE OR REPLACE VIEW DAT_CON_PRO_SYNCH_CONNECTION  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION, ARG3 AS DATASOURCELIBRARYID FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_pro' AND LOG_ACTION = 'synchronize_connection'
/

CREATE OR REPLACE VIEW DAT_CON_WP_SYNCH_CONNECTION  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION, ARG3 AS DATASOURCELIBRARYID FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_wp' AND LOG_ACTION = 'synchronize_connection'
/

CREATE OR REPLACE VIEW DAT_CON_PRO_UPDATE_CONNECTION  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION, ARG3 AS DATASOURCELIBRARYID FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_pro' AND LOG_ACTION = 'update_connection'
/

CREATE OR REPLACE VIEW DAT_CON_WP_UPDATE_CONNECTION  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION, ARG3 AS DATASOURCELIBRARYID FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_wp' AND LOG_ACTION = 'update_connection'
/

CREATE OR REPLACE VIEW DAT_CON_PRO_UPDATE_SOURCE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_pro' AND LOG_ACTION = 'update_source'
/

CREATE OR REPLACE VIEW DAT_CON_WP_UPDATE_SOURCE  AS SELECT LOGGED_TIME, MACHINE, USER_NAME, ORIGINAL_TIME, ORIGINAL_IP, SUCCESS, SESSION_ID, ID1 AS LIBRARYID, ID2 AS LIBRARYPATH, ARG1 AS DATASOURCETYPE, ARG2 AS DATASOURCEINFORMATION FROM ACTIONLOG WHERE LOG_CATEGORY = 'data_connector_wp' AND LOG_ACTION = 'update_source'
/


COMMIT
/

EXIT
/
